Change `@//` to `//` everywhere
In this cases, all of the `@//` paths were internal to `rules_scala`
itself.

Fixes the following test breakage:

```txt
$ RULES_SCALA_TEST_ONLY="test_scala_version 2.12.20" ./test_version.sh

running test test_scala_version 2.12.20
Starting local Bazel server and connecting to it...

ERROR: Error computing the main repository mapping:
  at .../test_version/test_scala_version_1733348149/scrooge_repositories.bzl:1:6:
  at .../external/rules_scala/scala/scala.bzl:45:5:
  at .../external/rules_scala/scala/private/rules/scala_test.bzl:14:5:
  at .../external/rules_scala/scala/private/phases/phases.bzl:62:6:
  at .../external/rules_scala/scala/private/phases/phase_declare_executable.bzl:6:6:

Label '//scala/private:rule_impls.bzl' is invalid because
  'scala/private' is not a package;
  perhaps you meant to put the colon here:
  '//:scala/private/rule_impls.bzl'?
```