WIP: Bzlmod part the ninety-third
Fixed the error mentioned in the previous commit by bumping every Scala
version up to `com.google.protobuf:protobuf-java:4.28.2`.

It really was that easy this time. Who knew?

For the record, this was the error across every Scala 2 version:

```txt
$ bazel test --repo_env=SCALA_VERSION=2.11.12 //test/scalafmt/...

INFO: Analyzed 9 targets (80 packages loaded, 3307 targets configured).
ERROR: .../test/scalafmt/BUILD:43:20: ScalaFmt
  test/scalafmt/test/scalafmt/formatted/formatted-test.scala.fmt.output
  failed: Worker process did not return a WorkResponse:

---8<---8<--- Start of log, file at .../bazel-workers/worker-134-ScalaFmt.log ---8<---8<---
Exception in thread "main" java.lang.NoSuchMethodError:
  'boolean com.google.protobuf.GeneratedMessageV3.isStringEmpty(java.lang.Object)'
```

This issue suggested a library bump may fix it, and it did:

- https://github.com/protocolbuffers/protobuf/issues/9236

Now the only tests failing are still the Scala 3 + Scalafmt tests from
`test_cross_build.sh`, but in a different way:

```txt
INFO: Analyzed target //scalafmt:formatted-binary3.format-test
  (0 packages loaded, 0 targets configured).
ERROR: .../external/rules_scala~/scala/scalafmt/BUILD:20:13:
  scala @@rules_scala~//scala/scalafmt:scalafmt [for tool] failed:
  (Exit 1): scalac failed: error executing Scalac command
  (from target @@rules_scala~//scala/scalafmt:scalafmt)

bazel-bin/external/rules_scala~/src/java/io/bazel/rulesscala/scalac/scalac
  ... (remaining 1 argument skipped)
error while loading Configured,
class file metaconfig/Configured.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
TASTy signature has wrong version.
 expected: {majorVersion: 28, minorVersion: 2}
 found   : {majorVersion: 28, minorVersion: 3}

This TASTy file was produced by a more recent, forwards incompatible release.
To read this TASTy file, please upgrade your tooling.
The TASTy file was produced by Scala 3.3.1.
***** missing reference, looking for ConfDecoderEx/T in package object metaconfig
decls = Scope{}
***** missing reference, looking for ConfCodecEx/T in package object metaconfig
decls = Scope{}
[ ...snipped many redundant instances of the above... ]

-- [E008] Not Found Error:
  external/rules_scala~/scala/scalafmt/scalafmt/ScalafmtWorker.scala:27:6
25 |    val config = ScalafmtConfig.fromHoconFile(
26 |      namespace.getOrElse("config", new File("")).toPath()
27 |    ).get
   |                 ^
   |value get is not a member of metaconfig.Configured[org.scalafmt.config.ScalafmtConfig]
2 errors found
Build failure with errors.
Target //scalafmt:formatted-binary3.format-test failed to build
```

This suggests I may need to create a new version of
`ScalafmtWorker.scala` specifically for Scala 3. Will look into that
now.