WIP: Bzlmod part the fortieth
Fixes a number of problems related to: `bazel test
//third_party/dependency_analyzer/src/test:scalac_dependency_test`.

Added `io_bazel_rules_scala_scala_{compiler,library,reflect}` repos as
dev dependencies.

Moved the remaining `setup_scala_toolchain()` calls from //scala to
@io_bazel_rules_scala_toolchains to fix missing dependencies.

Enabled compiler dependency tracking required by
//scala:unused_dependency_checker_error_toolchain, and registered that
toolchain as a dev dependency.

Got the hint to do this by diffing
bazel-bin/third_party/utils/src/test/test_util.jar-0.params from this
repo against that of my `WORKSPACE`-enabled repo and noticing the
unused_deps flags missing.

Still working on the following error:

```txt
ERROR: .../third_party/utils/src/test/BUILD:6:14:
  scala @@//third_party/utils/src/test:test_util failed: (Exit 1):
  scalac failed: error executing Scalac command
  (from target //third_party/utils/src/test:test_util)
  bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/src/java/io/bazel/rulesscala/scalac/scalac
  @bazel-out/darwin_arm64-fastbuild/bin/third_party/utils/src/test/test_util.jar-0.params

third_party/utils/src/test/io/bazel/rulesscala/utils/TestUtil.scala:10:
  error: object cmd is not a member of package tools
    import scala.tools.cmd.CommandLineParser
                       ^
third_party/utils/src/test/io/bazel/rulesscala/utils/TestUtil.scala:119:
  error: not found: value CommandLineParser
    val options = CommandLineParser.tokenize(compileOptions)
                  ^
```