WIP: Bzlmod part the seventy-seventh
Create the `@scala_compiler_sources` repo with aliases to versioned
`@scala_compiler_sources` repo targets.

So it turns out the `dep_reporting_compiler` target had a
version-specific repo reference in its `srcs` attribute. I'd worked
around this breakage by adding `scala_compiler_source` to the versioned
repos imported from `dev_deps`.

However, I got the following error after removing that reference, which
replicated an error I got while Bzlmodifying
`dt_patches/test_dt_patches`:

```txt
$ bazel build //src/...

ERROR: no such package
  '@@[unknown repo 'scala_compiler_source_2_13_14' requested from @@]//':
  The repository
  '@@[unknown repo 'scala_compiler_source_2_13_14' requested from @@]'
  could not be resolved:
  No repository visible as '@scala_compiler_source_2_13_14' from
    main repository

ERROR: .../third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/compiler/BUILD:5:39:
  no such package
  '@@[unknown repo 'scala_compiler_source_2_13_14' requested from @@]//':
  The repository '@@[unknown repo 'scala_compiler_source_2_13_14' requested from @@]'
  could not be resolved:
  No repository visible as '@scala_compiler_source_2_13_14' from
    main repository and referenced by
    '//third_party/dependency_analyzer/src/main/io/bazel/rulesscala/dependencyanalyzer/compiler:dep_reporting_compiler'

ERROR: Analysis of target '//src/java/io/bazel/rulesscala/scalac:scalac' failed; build aborted: Analysis failed
```

So now we have a `@scala_compiler_sources` repo containing aliases to
the other repos. Another level of indirection, another problem solved.