Bump to `rules_java` 7.12.2
Bazel 6.5.0 builds.

Bazel 7.4.1 fails with the same error mentioned in #1619. See the notes
under "Bump to rules_java 7.9.0 for Bazel 7 compatibility" from commit
cd22d8896f209c37be8622f1dcc9770c2dc18f48:

```txt
$ USE_BAZEL_VERSION=7.4.1 bazel build \
    //{src,jmh,test,third_party,scala_proto}/...

ERROR: .../external/rules_java_builtin/toolchains/BUILD:254:14:
  While resolving toolchains for target
  @@rules_java_builtin//toolchains:platformclasspath (096dcc8):
  No matching toolchains found for types
  @@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type.

ERROR: Analysis of target '//test/toolchains:java21_toolchain' failed;
  build aborted: Analysis failed
```

Bazel 8.0.0rc6 and 8.0.0rc7 fail as described in the previous commit.

---

Without the `WORKSPACE` updates from earlier, Bazel 6.5.0 fails with a
similar error to 7.4.1 with the `WORKSPACE` update:

```txt
$ bazel build //{src,jmh,test,third_party,scala_proto}/...

[ ...snip... ]
ERROR: .../rules_java/toolchains/BUILD:285:14:
  While resolving toolchains for target
  @rules_java//toolchains:platformclasspath:
  No matching toolchains found for types
  @rules_java//toolchains:bootstrap_runtime_toolchain_type.

ERROR: Analysis of target '//test:CheckBytecodeMajorVersion' failed;
  build aborted:
```

Bazel 7.4.1 fails with a different error:

```txt
$ bazel build //{src,jmh,test,third_party,scala_proto}/...

ERROR: .../external/remote_java_tools_darwin_arm64/BUILD: no such target
  '@@remote_java_tools_darwin_arm64//:prebuilt_one_version':
  target 'prebuilt_one_version' not declared in package ''
  defined by .../external/remote_java_tools_darwin_arm64/BUILD

ERROR: .../external/rules_java/toolchains/BUILD:163:14: no such target
  '@@remote_java_tools_darwin_arm64//:prebuilt_one_version':
  target 'prebuilt_one_version' not declared in package ''
  defined by .../external/remote_java_tools_darwin_arm64/BUILD
  and referenced by
  '@@rules_java//toolchains:prebuilt_one_version_darwin_arm64'

ERROR: Analysis of target
  '//test/src/main/resources/java_sources:CompiledWithJava8' failed;
  build aborted: Analysis failed
```