WIP: Bzlmod part the forty-fourth
Remove the unused `@com_google_protobuf//:protobuf_java` dependency from
//test/proto/custom_generator:FailingGenerator. Guess that unused dep
toolchain did its work.

```txt
ERROR: .../test/proto/custom_generator/BUILD.bazel:68:14:
  scala @@//test/proto/custom_generator:FailingGenerator failed:
  (Exit 1): scalac failed: error executing Scalac command
  (from target //test/proto/custom_generator:FailingGenerator)
  bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/src/java/io/bazel/rulesscala/scalac/scalac
  @bazel-out/darwin_arm64-fastbuild/bin/test/proto/custom_generator/FailingGenerator.jar-0.params

error: Unused dependencies:
error: Target '@com_google_protobuf//java/core:core'
  (via jar: ' bazel-out/darwin_arm64-fastbuild/bin/external/protobuf~/java/core/libcore.jar ')
  is specified as a dependency to //test/proto/custom_generator:FailingGenerator
  but isn't used, please remove it from the deps.

You can use the following buildozer command:
  buildozer 'remove deps @com_google_protobuf//java/core:core' //test/proto/custom_generator:FailingGenerator

error: Target '@com_google_protobuf//java/core:core'
  (via jar: ' bazel-out/darwin_arm64-fastbuild/bin/external/protobuf~/java/core/liblite_runtime_only.jar ')
  is specified as a dependency to //test/proto/custom_generator:FailingGenerator
  but isn't used, please remove it from the deps.

You can use the following buildozer command:
  buildozer 'remove deps @com_google_protobuf//java/core:core' //test/proto/custom_generator:FailingGenerator
```