Bump protobuf to v25.5
This works under Bazel 7. However, it breaks Bazel 6 support:

```txt
ERROR: .../external/com_google_absl/absl/base/BUILD.bazel:53:11:
  Compiling absl/base/log_severity.cc [for tool] failed:
  (Exit 1): wrapped_clang_pp failed: error executing command
  (from target @com_google_absl//absl/base:log_severity)

external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1'
  -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety
  -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG
  ... (remaining 66 arguments skipped)

In file included from external/com_google_absl/absl/base/log_severity.cc:15:
In file included from external/com_google_absl/absl/base/log_severity.h:21:
In file included from external/com_google_absl/absl/base/attributes.h:37:
In file included from external/com_google_absl/absl/base/config.h:86:
external/com_google_absl/absl/base/policy_checks.h:79:2:
  error: "C++ versions less than C++14 are not supported."
   79 | #error "C++ versions less than C++14 are not supported."
      |  ^
```