WIP: Bzlmod part the eighty-second
Got `./test-lint.sh` working again by reverting the `buildtools` module
import and applying a `go_deps` hack.

The original `buildtools` module import kept reporting:

```txt
ERROR: Analysis of target '//tools:lint_check' failed; build aborted:
  module extension "go_deps" from "@@gazelle~//:extensions.bzl"
  does not generate repository "com_github_bazelbuild_buildtools",
  yet it is imported as "com_github_bazelbuild_buildtools"
  in the usage at
  https://bcr.bazel.build/modules/gazelle/0.37.0/MODULE.bazel:29:24
```

And then the plain `http_archive()` import caused:

```txt
ERROR: no such package
  '@@[unknown repo 'com_github_golang_protobuf' requested from
  @@_main~_repo_rules~com_github_bazelbuild_buildtools]//proto':
  The repository '@@[unknown repo 'com_github_golang_protobuf'
  requested from @@_main~_repo_rules~com_github_bazelbuild_buildtools]'
  could not be resolved:
  No repository visible as '@com_github_golang_protobuf'
  from repository '@@_main~_repo_rules~com_github_bazelbuild_buildtools'

ERROR: .../external/_main~_repo_rules~com_github_bazelbuild_buildtools/edit/BUILD.bazel:3:11:
  no such package '@@[unknown repo 'com_github_golang_protobuf'
  requested from @@_main~_repo_rules~com_github_bazelbuild_buildtools]//proto':
  The repository '@@[unknown repo 'com_github_golang_protobuf'
  requested from @@_main~_repo_rules~com_github_bazelbuild_buildtools]'
  could not be resolved:
  No repository visible as '@com_github_golang_protobuf'
  from repository '@@_main~_repo_rules~com_github_bazelbuild_buildtools'
  and referenced by
  '@@_main~_repo_rules~com_github_bazelbuild_buildtools//edit:go_default_library'

ERROR: Analysis of target '//tools:lint_check' failed;
  build aborted: Analysis failed
```

Now it produces the mildly annoying warning:

```txt
WARNING: .../MODULE.bazel:194:24:
  The module extension go_deps
  defined in @gazelle//:extensions.bzl
  reported incorrect imports of repositories via use_repo():

Imported, but reported as indirect dependencies by the extension:
  com_github_golang_protobuf

Fix the use_repo calls by running 'bazel mod tidy'.
```

I'll apply the fixes from `bazel run //tools:lint_fix` in the next
commit. Really wish I'd done this long ago.