WIP: Bzlmod part the seventieth
Got examples/semanticdb building with Bzlmod, and almost have
examples/crossbuild working. Have to fix:

```txt
ERROR: .../external/rules_scala~/testing/toolchain/BUILD:13:27:
  in testing_toolchain_deps rule
  @@rules_scala~//testing/toolchain:scalatest_classpath:

Traceback (most recent call last):
  File ".../external/rules_scala~/testing/toolchain/toolchain_deps.bzl",
    line 9, column 33, in _testing_toolchain_deps
    return expose_toolchain_deps(ctx, _toolchain_type)
  File ".../external/rules_scala~/scala/private/toolchain_deps/toolchain_deps.bzl",
    line 22, column 34, in expose_toolchain_deps
    deps_info = find_deps_info_on(ctx, toolchain_type_label, deps_id)
  File ".../external/rules_scala~/scala/private/toolchain_deps/toolchain_deps.bzl",
    line 18, column 34, in find_deps_info_on
    return _lookup_provider_by_id(ctx, toolchain_type_label, dep_providers, deps_id)[DepsInfo]
  File ".../external/rules_scala~/scala/private/toolchain_deps/toolchain_deps.bzl",
    line 11, column 9, in _lookup_provider_by_id
    fail("%s requires mapping of %s provider id on the toolchain %s" % (

Error in fail: @@rules_scala~//testing/toolchain:scalatest_classpath
  requires mapping of
  @io_bazel_rules_scala//testing/toolchain:testing_toolchain_type
  provider id on the toolchain scalatest_classpath_3_3_3

ERROR: .../external/rules_scala~/testing/toolchain/BUILD:13:27: Analysis
  of target '@@rules_scala~//testing/toolchain:scalatest_classpath' failed

ERROR: Analysis of target '//1_single:test213' failed; build aborted: Analysis failed
```