Fix `dt_patches/dt_patch_test.sh` for Scala 2.13.0
Updates targets broken under the Scala 2.13.0 test. Also removes the
redundant 2.12.1 test, and cleans the `test_dt_patches_user_srcjar` repo
before the `test_compiler_srcjar{,_nonhermetic}` tests. Part of #1482.

This fix and the `.bazelversion` sync from #1629 can land in either
order. Both are required for `dt_patches/dt_patch_test.sh` to be fully
functional.

---

The equivalent standalone command in `dt_patches/test_dt_patches`
produced the error:

```txt
$ bazel build //... --repo_env=SCALA_VERSION=2.13.0 //...

ERROR: .../rules_scala~/src/java/io/bazel/rulesscala/scalac/reporter/BUILD:5:13:
  Building external/rules_scala~/src/java/io/bazel/rulesscala/scalac/reporter/libreporter.jar
  (2 source files) [for tool] failed: (Exit 1): java failed:
  error executing Javac command
  (from target @@rules_scala~//src/java/io/bazel/rulesscala/scalac/reporter:reporter)
  external/rules_java~~toolchains~remotejdk21_macos_aarch64/bin/java
    '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED'
    '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ...
    (remaining 19 arguments skipped)

external/rules_scala~/src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/
  after_2_12_13_and_before_2_13_12/DepsTrackingReporter.java:85:
  error: method does not override or implement a method from a supertype
  @Override
  ^

external/rules_scala~/src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/
  after_2_12_13_and_before_2_13_12/DepsTrackingReporter.java:94:
  error: cannot find symbol
    ((FilteringReporter) delegateReporter).doReport(pos, msg, severity);
                                          ^
  symbol:   method doReport(Position,String,Reporter.Severity)
  location: interface FilteringReporter

external/rules_scala~/src/java/io/bazel/rulesscala/scalac/deps_tracking_reporter/after_2_12_13_and_before_2_13_12/DepsTrackingReporter.java:99:
  error: cannot find symbol
    super.doReport(pos, msg, severity);
         ^
  symbol: method doReport(Position,String,Reporter.Severity)

external/rules_scala~/src/java/io/bazel/rulesscala/scalac/reporter/after_2_12_13_and_before_2_13_12/ProtoReporter.java:49:
  error: method does not override or implement a method from a supertype
    @Override
    ^

external/rules_scala~/src/java/io/bazel/rulesscala/scalac/reporter/after_2_12_13_and_before_2_13_12/ProtoReporter.java:51:
  error: cannot find symbol
    super.doReport(pos, msg, severity);
         ^
  symbol: method doReport(Position,String,Reporter.Severity)

Target //dummy:dummy failed to build
```

I had the thought that maybe 2.13.0 could use the same `srcs` as the
`before_2_12_13` targets. So I abused the `any` matcher to pick exactly
2.13.0 and assign it the same values as `before_2_12_13`. Now it works,
and `dt_patches/dt_patch_test.sh` fully passes.

---

Cleaning the `test_dt_patches_user_srcjar` repository helps ensure that
the `test_compiler_srcjar_nonhermetic` runs, in particular, don't fail
after the first run.