WIP: Bzlmod part the eighty-first
Fixed inverted conditional in the `scala_deps` extension that caused all
the srcjar tests to fail. Also tweaked some of the `compiler_srcjar`
tags to trigger failures equivalent to those configured by `WORKSPACE`.

Now all the test cases pass but two. The first one, `test_compiler_patch
2.13.0`, also currently fails on `master` using `WORKSPACE`.

The second one is `test_compiler_srcjar 2.12.16`, which tries to use a
`label` in its `compiler_srcjar` tag:

```py
scala_deps.compiler_srcjar(
    version = "2.12.16",
    label = "@scala_compiler_srcjar//jar:downloaded.jar",
)
```

Replicating the test failure by executing the following command directly
in the `dt_patches/test_dt_patches_user_srcjar` repo produces:

```txt
$ bazel build //... --repo_env=SCALA_VERSION=2.12.16 //...

ERROR: Traceback (most recent call last):
  File ".../external/rules_scala~/scala/extensions/deps.bzl",
    line 148, column 38, in _scala_deps_impl
    dt_patched_compiler_setup(version, srcjars.get(version))
  File ".../external/rules_scala~/scala/private/macros/scala_repositories.bzl",
    line 100, column 28, in dt_patched_compiler_setup
    dt_patched_compiler(

Error in repository_rule:
  no repository visible as '@scala_compiler_srcjar'
  to the repository '@@rules_scala~',
  but referenced by label '@scala_compiler_srcjar//jar:downloaded.jar'
  in attribute 'srcjar' of dt_patched_compiler
  'scala_compiler_source_2_12_16'.

  Is the module 'rules_scala' missing a bazel_dep or
  use_repo(..., "scala_compiler_srcjar")?

ERROR: Analysis of target '//dummy:dummy' failed; build aborted:
  error evaluating module extension scala_deps
  in @@rules_scala~//scala/extensions:deps.bzl
```

I'll have to think hard on that, as Bzlmod repo visibility rules seem to
stymie passing in a `Label` to a user's own repo.