WIP: Bzlmod part the forty-first
Provide our own `scala.tools.cmd.CommandLineParser` for Scala >=2.13.9
to fix //third_party/utils/src/test:test_util.

OMG this was a weird one. First, the error:

```txt
ERROR: .../third_party/utils/src/test/BUILD:6:14:
  scala @@//third_party/utils/src/test:test_util failed: (Exit 1):
  scalac failed: error executing Scalac command
  (from target //third_party/utils/src/test:test_util)
  bazel-out/darwin_arm64-opt-exec-ST-d57f47055a04/bin/src/java/io/bazel/rulesscala/scalac/scalac
  @bazel-out/darwin_arm64-fastbuild/bin/third_party/utils/src/test/test_util.jar-0.params

third_party/utils/src/test/io/bazel/rulesscala/utils/TestUtil.scala:10:
  error: object cmd is not a member of package tools
    import scala.tools.cmd.CommandLineParser
                       ^
third_party/utils/src/test/io/bazel/rulesscala/utils/TestUtil.scala:119:
  error: not found: value CommandLineParser
    val options = CommandLineParser.tokenize(compileOptions)
                  ^
```

Turned out this `CommandLineParser` disappered in Scala 2.13.9, and its
`Parser` replacement was private (so much for semantic versioning...):

- https://github.com/scala/scala/pull/10057

No wonder `rules_scala` has `select_for_scala_version`. Damn.