Force rebuild of #1710 due to Windows failure
Got an odd failure on the Windows build:

- https://buildkite.com/bazel/rules-scala-scala/builds/5394#01954e5a-8f5b-4880-befa-1bce0d21d512/75-179

```txt
ERROR:
  C:/tools/msys64/home/b/_bazel_b/xknd5zlq/external/com_google_protobuf/src/google/protobuf/compiler/java/BUILD.bazel:87:11:
  Compiling src/google/protobuf/compiler/java/java_features.pb.cc
  [for tool] failed: (Exit 2):
  cl.exe failed: error executing CppCompile command
  (from target @@com_google_protobuf//src/google/protobuf/compiler/java:java_features_bootstrap)
  C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.39.33519\bin\HostX64\x64\cl.exe ...
(remaining 1 argument skipped)
--
  | external/com_google_protobuf/src/google/protobuf/compiler/java/java_features.pb.cc(6):
    fatal error C1083: Cannot open include file:
    'google/protobuf/compiler/java/java_features.pb.h':
    No such file or directory
```

`src/google/protobuf/compiler/java/java_features.pb.h` most definitely
exists in protobuf v29.3:

- https://github.com/protocolbuffers/protobuf/blob/v29.3/src/google/protobuf/compiler/java/java_features.pb.h

All the other builds passed. Kicking the pull requeest branch with this
empty commit to see if the Windows build will pass, in case it was some
weird transient error.