WIP: Bzlmod part the one hundred-eighteenth
Fix testing toolchain configuration errors

Also introduces `register_testing_toolchains` to make
`{scalatest,junit,specs2_junit}_toolchain` compatible with the
new toolchains repo. They aren't separate toolchains anymore; there's a
single testing toolchain per Scala version that contains all testing
frameworks configured via `scala_toolchains`.

The error below happened when building under `--noenable_bzlmod
--enable_workspace` until I properly propagated `scalatest = True` when
`testing == True` in `scala_toolchains`. I don't know how the Bzlmod
builds passed without this change.

```txt
$ bazel build //src/...

ERROR: no such package '@@io_bazel_rules_scala_scalatest_shouldmatchers_2_12_20//':
  The repository '@@io_bazel_rules_scala_scalatest_shouldmatchers_2_12_20'
  could not be resolved:
  Repository '@@io_bazel_rules_scala_scalatest_shouldmatchers_2_12_20' is not defined

ERROR: .../external/io_bazel_rules_scala_toolchains/testing/BUILD:13:34:
  no such package '@@io_bazel_rules_scala_scalatest_shouldmatchers_2_12_20//':
  The repository '@@io_bazel_rules_scala_scalatest_shouldmatchers_2_12_20'
  could not be resolved:
  Repository '@@io_bazel_rules_scala_scalatest_shouldmatchers_2_12_20' is not defined
  and referenced by
  '@@io_bazel_rules_scala_toolchains//testing:testing_toolchain_2_12_20_scalatest_classpath_provider'

ERROR: Analysis of target
  '//src/java/io/bazel/rulesscala/scala_test:runner' failed;
  build aborted: Analysis failed
```