WIP: Bzlmod part the one hundred nineteenth
Fix twitter_scrooge for test_versions.sh

Also fixes a minor failure in `dt_patch_test` when expecting an error
from the 2.12.12 srcjar.

With this change, both `--enable_bzlmod --noenable_workspace` and
`--noenable_bzlmod --enable_workspace` builds pass, at least for Bazel
7.4.0.

Without the updates to support `twitter_scrooge`, `test_versions.sh`
would fail with:

```txt
ERROR: .../test_version/test_scala_version_1730076151/BUILD:18:12:
  While resolving toolchains for target //:JavaBinary (096dcc8):
  invalid registered toolchain
  '@io_bazel_rules_scala_toolchains//twitter_scrooge:scrooge_toolchain':
  no such package '@@io_bazel_rules_scala_toolchains//twitter_scrooge':
  BUILD file not found in directory 'twitter_scrooge' of external
  repository @@io_bazel_rules_scala_toolchains.
  Add a BUILD file to a directory to mark it as a package.

ERROR: Analysis of target '//:JavaBinary' failed; build aborted
```

---

Also, with this change, I'm pretty sure all the old `native.bind()`
calls are bypassed in both `WORKSPACE` and Bzlmod modes. I'll try to
remove them next.