Bump to Bazel 8.0.0rc6
`//third_party/dependency_analyzer/src/test:strict_deps_test`
and
`//third_party/dependency_analyzer/src/test:unused_dependency_checker_test`
both fail with errors of the form:

```txt
StrictDepsTest:
- error on indirect dependency target *** FAILED *** (379 milliseconds)
  nice errors on sequence of strings.this.infos.exists(nice errors on
  sequence of strings.this.checkErrorContainsMessage(target)) was false
  expected an error on //commons:Target to appear in errors (with
  buildozer command)!
  Errors: List(object apache is not a member of package org)
  (StrictDepsTest.scala:85)
```

This happens both under `WORKSPACE` and Bzlmod.

These targets both depend on
`@org_apache_commons_commons_lang_3_5_without_file//:linkable_org_apache_commons_commons_lang_3_5_without_file`.
The `@org_apache_commons_commons_lang_3_5_without_file` repo is now
instantiated by `dev_deps_repositories()` from
`scala/private/extensions/dev_deps.bzl`. These tests pass before Bazel
8.

I added code to the "error on indirect dependency target" test case
from `third_party/dependency_analyzer/src/test/io/bazel/rulesscala/
dependencyanalyzer/StrictDepsTest.scala` to see the result of
`compileWithDependencyAnalyzer()`:

```diff
diff --git a/third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/StrictDepsTest.scala b/third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/StrictDepsTest.scala
index b26ba5e5..76b19e90 100644
--- a/third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/StrictDepsTest.scala
+++ b/third_party/dependency_analyzer/src/test/io/bazel/rulesscala/dependencyanalyzer/StrictDepsTest.scala
@@ -37,7 +37,9 @@ class StrictDepsTest extends AnyFunSuite {
     val commonsTarget = "//commons:Target"

     val indirect = List(apacheCommonsClasspath -> commonsTarget)
-    compileWithDependencyAnalyzer(testCode, withIndirect = indirect).expectErrorOn(commonsTarget)
+    val errors = compileWithDependencyAnalyzer(testCode, withIndirect = indirect)
+    System.out.println(errors)
+    errors.expectErrorOn(commonsTarget)
   }

   test("error on multiple indirect dependency targets") {
```

Under Bazel 7.4.1, the test passes and shows this output:

```txt
$ bazel test --test_output=streamed \
  //third_party/dependency_analyzer/src/test:strict_deps_test

[ ...snip... ]
StrictDepsTest:
List(Target '//commons:Target' is used but isn't explicitly declared, please add it to the deps.
You can use the following buildozer command:
buildozer 'add deps //commons:Target' //...)
```

Under Bazel 8.0.0rc6, it fails and shows this, matching the output mentioned
earlier:

```txt
$ bazel test --test_output=streamed \
  //third_party/dependency_analyzer/src/test:strict_deps_test

[ ...snip... ]
StrictDepsTest:
List(object apache is not a member of package org)
```

Still investigating...