Move `scala/{private/macros/,}toolchains_repo.bzl`
Like "Move `scala_toolchains` to `scala/toolchains.bzl`",
removes the `scala_toolchains_repo` symbol from `scala/scala.bzl` and
makes it available from `scala/toolchains_repo.bzl`.

With this change, `rules_scala` successfully builds and passes all its
tests when building under `WORKSPACE` and Bzlmod using Bazel 8.0.0rc6.

Resolves the following `test_scala_version 2.12.20` failure during Bazel
8 builds by ensuring `WORKSPACE` doesn't transitively `load()` any
`.bzl` files referencing `rules_java` symbols. It turned out that
`test_version/version_specific_tests_dir/scrooge_repositories.bzl`,
copied into a new `test_version/test_scala_version_...` directory during
the test, called `load("@rules_scala//scala/scala.bzl",
"toolchains_repo")`.

```txt
$ RULES_SCALA_TEST_ONLY="test_scala_version 2.12.20" ./test_version.sh

ERROR: Traceback (most recent call last):
  File ".../external/rules_scala/scala/private/common_attributes.bzl",
  line 18, column 28, in <toplevel>
    "deps": attr.label_list(

Error in label_list:
  Illegal argument: element in 'providers' is of unexpected type.
  Either all elements should be providers,
  or all elements should be lists of providers,
  but got list with an element of type NoneType.

ERROR: Error computing the main repository mapping:
  at test_version/test_scala_version_.../scrooge_repositories.bzl:1:6:
  at .../scala/scala.bzl:30:5:
  at .../scala/private/rules/scala_junit_test.bzl:5:5:
initialization of module 'scala/private/common_attributes.bzl' failed
```